name: 'Create Pull Request'
description: 'Creates a pull request for changes to your repository in the actions workspace'
inputs:
  token:
    description: 'The token that the action will use to create the pull request.'
    required: true
  branch:
    description: 'The branch name for the pull request.'
    required: true
  title:
    description: 'The title of the pull request.'
    required: true
  body:
    description: 'The body of the pull request.'
    required: true
outputs:
  pull-request-url:
    description: 'The URL of the created pull request.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
