name: Commit and PR

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout copilot-files branch
        uses: actions/checkout@v2
        with:
          ref: copilot-files

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create a new branch
        run: |
          BRANCH_NAME="auto-commit-$(date +%Y%m%d)"
          git checkout -b $BRANCH_NAME

      - name: Make changes
        run: |
          DAY=$(date +%d) # Get the day of the month
          FILE="copilot$(( DAY % 4 + 1 )).md" # Cycle through copilot1.md, copilot2.md, copilot3.md, copilot4.md
          cat $FILE >> ../completions.md # Append the content to completions.md
          git add ../completions.md

      - name: Commit changes
        run: |
          git commit -m "Automated commit for $(date)"

      - name: Push changes
        run: |
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $BRANCH_NAME
          title: "Automated PR for $(date)"
          body: "This is an automated PR created by GitHub Actions."

      - name: Merge Pull Request
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ steps.create_pr.outputs.pull_request_number }};
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: 'merge'
            });

      - name: Delete branch
        run: |
          git push origin --delete $BRANCH_NAME
